name: Bug Report
description: Report a bug or issue
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which Groo product is this about?
      options:
        - Pass
        - Drive
        - Pad
        - Groo for macOS
        - Accounts
        - AI
        - Ops
        - Docs
        - groo (CLI)
        - cl (CLI)
        - record-release
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Web
        - Chrome Extension
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (browser version, OS version, etc.)
    validations:
      required: false
