name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which Groo product is this for?
      options:
        - Pass
        - Drive
        - Pad
        - Groo for macOS
        - Accounts
        - AI
        - Ops
        - Docs
        - groo (CLI)
        - cl (CLI)
        - record-release
        - Other
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: What problem does this solve? Why do you need this?
      placeholder: This would help me...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
    validations:
      required: false
